name: Pull Request Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  PR:
    name: Execute Pull Request Workflow
    if: ${{ !contains(github.event.head_commit.message, '[CI Skip]') }}
    uses: Olipro/Interceptify/.github/workflows/ci.yml@github
    with:
      isRelease: false
      isPR: true
    secrets:
      GITHUBTOKEN: ${{secrets.GITHUB_TOKEN}}
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      OSSRH_USER: 'null'
      OSSRH_PASS: 'null'
      OSSRH_KEY: 'null'
      OSSRH_KEYPASS: 'null'

