name: Release Pipeline

on:
  push:
    tags: ['v*']

jobs:
  Release:
    name: Execute Release Workflow
    if: ${{ !contains(github.event.head_commit.message, '[CI Skip]') }}
    uses: Olipro/Interceptify/.github/workflows/ci.yml@github
    with:
      isRelease: true
    secrets:
      GITHUBTOKEN: ${{secrets.GITHUB_TOKEN}}
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      OSSRH_USER: ${{secrets.OSSRH_USER}}
      OSSRH_PASS: ${{secrets.OSSRH_PASS}}
      OSSRH_KEY: ${{secrets.OSSRH_KEY}}
      OSSRH_KEYPASS: ${{secrets.OSSRH_KEYPASS}}

