name: Snapshot Pipeline

on:
  push:
    branches: [$default-branch]
    tags-ignore: ['*']
  workflow_dispatch:

jobs:
  Snapshot:
    name: Execute Snapshot Workflow
    if: ${{ !contains(github.event.head_commit.message, '[CI Skip]') && github.event_name != 'pull_request' }}
    uses: Olipro/Interceptify/.github/workflows/ci.yml@github
    with:
      isRelease: false
    secrets:
      GITHUBTOKEN: ${{secrets.GITHUB_TOKEN}}
      SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
      OSSRH_USER: ${{secrets.OSSRH_USER}}
      OSSRH_PASS: ${{secrets.OSSRH_PASS}}
      OSSRH_KEY: ${{secrets.OSSRH_KEY}}
      OSSRH_KEYPASS: ${{secrets.OSSRH_KEYPASS}}
